add news sync script files
Alann27/somos-pueblo pull request #2
Opened 2021-07-19 22:56 UTC by Alann27

The file "app.js" is the index. The axios module is used to make HTTP request to Wordpress and get the news, categories and images. The module "aws-sdk" is for upload the images to digital ocean spaces and the file "spaces.js" content all the code relative to it. In the file "new-sync.js" is a function called "InitCollections" that get the new news and categories.

2021-07-20 15:01 UTC, carmensanchez1 commented on newsync/index.js
> +const lastCategorie = "/wp-json/wp/v2/categories?per_page=1&orderby=id&order=desc";
if hostname, lastNew and lastCategorie (is lastCatergory) can be in .env file so will be easier to change in case it's needed or in a file constants.js

2021-07-20 20:25 UTC, carmensanchez1 commented on newsync/models/news.js
> +        'wordpress-id': {
this can be better wordpress_id

2021-07-20 20:25 UTC, carmensanchez1 commented on newsync/models/categories.js
> +        'wordpress-id': {
this can be better wordpress_id

2021-07-21 21:11 UTC, jhenriquez requested changes
Overall good progress, but specially the fault tolerance is what worries me the most.

2021-07-21 21:11 UTC, jhenriquez commented on newsync/spaces.js
> +class Spaces{
I wouldn't call this spaces, I would use a more generic name like FileUploadManager, same for the environment variables associated.

2021-07-21 21:11 UTC, jhenriquez commented on newsync/spaces.js
> +        const responseImage = await axios.get(url, { responseType: "stream" });
I would suggest we try and see if we can upload directly from the URL. If that is not possible, we should then proceed to upload as stream. See [here](https://stackoverflow.com/a/37366093/430969)

2021-07-21 21:11 UTC, jhenriquez commented on newsync/spaces.js
> +
What is this stored location? I believe when accessing S3 items you'll need to know the Key. I'm not sure what this location is.

2021-07-21 21:11 UTC, jhenriquez commented on newsync/spaces.js
> +
Also, I believe the key for images, should be a conbination of the id of the post and the slug name of the image, if that is possible. For instance:

`{postID}/{image-slug}` or even simpler `{post-slug}-{index}` what this means is that if you have a post slugged: "the-big-news" that has one image:

The key would be: "the-big-news-0", if would have multiple it would be "the-big-news-0...n"

2021-07-22 15:58 UTC, Alann27 commented on newsync/spaces.js
> +        const responseImage = await axios.get(url, { responseType: "stream" });
That's already implemented. The path module it's only used to get the extension of the image (.jpg, .png, etc) directly from the image's URL provided by Wordpress.

2021-07-22 16:14 UTC, Alann27 commented on newsync/spaces.js
> +
The stored.Location is the URL of the image provided by the S3. Right now every post only have one image, that's why I put the key only with the postID.

Do you sugest we use an array of the URLs (even when a post only have one image) to manage the posible case when a post has more than one image?

2021-07-23 18:13 UTC, carmensanchez1 requested changes

2021-07-23 18:13 UTC, carmensanchez1 commented on newsync/index.js
> +const categoriesOnDB = await Categories.find().select({'wordpress-id': 1, name: 1, slug: 1, _id: 0});
this should be inside a function with try/catch in order to handle error in case it happens

2021-07-23 18:13 UTC, carmensanchez1 commented on newsync/index.js
> +                    await model.insertMany(itemsArray);
what happens if something happens while inserting? try using try/catch to handle in case it happens. You can create a new function to do the insert and add all the logic there and just call the function

2021-08-03 00:39 UTC, carmensanchez1 approved these changes

2021-08-23 16:08 UTC, closed without merging